fix(passkeys): get actual identifier field (e.g. email) instead of username, to allow for custom user models
Exception: Can't find 'passkeys' key in request.POST, did you add the hidden input?